#!/bin/bash

# realpath for OSX
# https://stackoverflow.com/a/3572105
function realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

function usage() {
    echo "Usage: $0 path [port]"
    exit 1
}

OPTIONS=""

if [ $# -lt 1 ]; then
    DIR="."
else
    DIR=$1
fi

# Note that mounting user's home directory results in high CPU if
# Docker "use gRPC FUSE" for file sharing is enabled.
OPTIONS=$OPTIONS" --mount type=bind,source=$(realpath $DIR),target=/mnt "
OPTIONS=$OPTIONS" --mount type=bind,source=${HOME}/.m2,target=/home/developer/.m2 "

if [ $# -ge 2 ]; then
    PORT=$2
    echo "Docker port $PORT will be exposed at $PORT"

    OPTIONS=$OPTIONS" -p 127.0.0.1:$PORT:$PORT/tcp "
fi

docker run \
	-it \
	--hostname=cortex \
    $OPTIONS \
	cortex-development
